// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from "@tanstack/react-router"

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ConfigRouteRouteImport } from "./routes/config/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ConfigIndexRouteImport } from "./routes/config/index"

const ConfigUpstreamsLazyRouteImport = createFileRoute("/config/upstreams")()
const ConfigStrategyLazyRouteImport = createFileRoute("/config/strategy")()
const ConfigSettingsLazyRouteImport = createFileRoute("/config/settings")()
const ConfigDashboardLazyRouteImport = createFileRoute("/config/dashboard")()
const ConfigCoreLazyRouteImport = createFileRoute("/config/core")()

const ConfigRouteRoute = ConfigRouteRouteImport.update({
  id: "/config",
  path: "/config",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ConfigRouteRoute,
} as any)
const ConfigUpstreamsLazyRoute = ConfigUpstreamsLazyRouteImport.update({
  id: "/upstreams",
  path: "/upstreams",
  getParentRoute: () => ConfigRouteRoute,
} as any).lazy(() =>
  import("./routes/config/upstreams.lazy").then((d) => d.Route),
)
const ConfigStrategyLazyRoute = ConfigStrategyLazyRouteImport.update({
  id: "/strategy",
  path: "/strategy",
  getParentRoute: () => ConfigRouteRoute,
} as any).lazy(() =>
  import("./routes/config/strategy.lazy").then((d) => d.Route),
)
const ConfigSettingsLazyRoute = ConfigSettingsLazyRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => ConfigRouteRoute,
} as any).lazy(() =>
  import("./routes/config/settings.lazy").then((d) => d.Route),
)
const ConfigDashboardLazyRoute = ConfigDashboardLazyRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => ConfigRouteRoute,
} as any).lazy(() =>
  import("./routes/config/dashboard.lazy").then((d) => d.Route),
)
const ConfigCoreLazyRoute = ConfigCoreLazyRouteImport.update({
  id: "/core",
  path: "/core",
  getParentRoute: () => ConfigRouteRoute,
} as any).lazy(() => import("./routes/config/core.lazy").then((d) => d.Route))

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/config": typeof ConfigRouteRouteWithChildren
  "/config/core": typeof ConfigCoreLazyRoute
  "/config/dashboard": typeof ConfigDashboardLazyRoute
  "/config/settings": typeof ConfigSettingsLazyRoute
  "/config/strategy": typeof ConfigStrategyLazyRoute
  "/config/upstreams": typeof ConfigUpstreamsLazyRoute
  "/config/": typeof ConfigIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/config/core": typeof ConfigCoreLazyRoute
  "/config/dashboard": typeof ConfigDashboardLazyRoute
  "/config/settings": typeof ConfigSettingsLazyRoute
  "/config/strategy": typeof ConfigStrategyLazyRoute
  "/config/upstreams": typeof ConfigUpstreamsLazyRoute
  "/config": typeof ConfigIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/config": typeof ConfigRouteRouteWithChildren
  "/config/core": typeof ConfigCoreLazyRoute
  "/config/dashboard": typeof ConfigDashboardLazyRoute
  "/config/settings": typeof ConfigSettingsLazyRoute
  "/config/strategy": typeof ConfigStrategyLazyRoute
  "/config/upstreams": typeof ConfigUpstreamsLazyRoute
  "/config/": typeof ConfigIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/config"
    | "/config/core"
    | "/config/dashboard"
    | "/config/settings"
    | "/config/strategy"
    | "/config/upstreams"
    | "/config/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/config/core"
    | "/config/dashboard"
    | "/config/settings"
    | "/config/strategy"
    | "/config/upstreams"
    | "/config"
  id:
    | "__root__"
    | "/"
    | "/config"
    | "/config/core"
    | "/config/dashboard"
    | "/config/settings"
    | "/config/strategy"
    | "/config/upstreams"
    | "/config/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfigRouteRoute: typeof ConfigRouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/config": {
      id: "/config"
      path: "/config"
      fullPath: "/config"
      preLoaderRoute: typeof ConfigRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/config/": {
      id: "/config/"
      path: "/"
      fullPath: "/config/"
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof ConfigRouteRoute
    }
    "/config/upstreams": {
      id: "/config/upstreams"
      path: "/upstreams"
      fullPath: "/config/upstreams"
      preLoaderRoute: typeof ConfigUpstreamsLazyRouteImport
      parentRoute: typeof ConfigRouteRoute
    }
    "/config/strategy": {
      id: "/config/strategy"
      path: "/strategy"
      fullPath: "/config/strategy"
      preLoaderRoute: typeof ConfigStrategyLazyRouteImport
      parentRoute: typeof ConfigRouteRoute
    }
    "/config/settings": {
      id: "/config/settings"
      path: "/settings"
      fullPath: "/config/settings"
      preLoaderRoute: typeof ConfigSettingsLazyRouteImport
      parentRoute: typeof ConfigRouteRoute
    }
    "/config/dashboard": {
      id: "/config/dashboard"
      path: "/dashboard"
      fullPath: "/config/dashboard"
      preLoaderRoute: typeof ConfigDashboardLazyRouteImport
      parentRoute: typeof ConfigRouteRoute
    }
    "/config/core": {
      id: "/config/core"
      path: "/core"
      fullPath: "/config/core"
      preLoaderRoute: typeof ConfigCoreLazyRouteImport
      parentRoute: typeof ConfigRouteRoute
    }
  }
}

interface ConfigRouteRouteChildren {
  ConfigCoreLazyRoute: typeof ConfigCoreLazyRoute
  ConfigDashboardLazyRoute: typeof ConfigDashboardLazyRoute
  ConfigSettingsLazyRoute: typeof ConfigSettingsLazyRoute
  ConfigStrategyLazyRoute: typeof ConfigStrategyLazyRoute
  ConfigUpstreamsLazyRoute: typeof ConfigUpstreamsLazyRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
}

const ConfigRouteRouteChildren: ConfigRouteRouteChildren = {
  ConfigCoreLazyRoute: ConfigCoreLazyRoute,
  ConfigDashboardLazyRoute: ConfigDashboardLazyRoute,
  ConfigSettingsLazyRoute: ConfigSettingsLazyRoute,
  ConfigStrategyLazyRoute: ConfigStrategyLazyRoute,
  ConfigUpstreamsLazyRoute: ConfigUpstreamsLazyRoute,
  ConfigIndexRoute: ConfigIndexRoute,
}

const ConfigRouteRouteWithChildren = ConfigRouteRoute._addFileChildren(
  ConfigRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfigRouteRoute: ConfigRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
